#https://medium.com/analytics-vidhya/getting-started-with-postgresql-using-docker-compose-34d6b808c47c

version: "3.2"
services:
  db:
    image: postgres
    restart: always
    container_name: pgsql_db
    env_file:
      - db.env
    volumes:
      # bind container's folder onto a host's folder
      - type: bind
        source: ./db_scripts
        target: /var/lib/postgresql/data/
      - db-data:/var/lib/postgresql/data/ #persist data inside the container
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build: .
    volumes:
      - type: bind
        source: ./src/backend
        target: /app/src/backend
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  db-data:
