export const exercises = [
  {
    week: 1,
    day: 1,
    exercise: "Snatch + Overhead Squat",
    instruction: "75% 1r4s",
  },
  {
    week: 1,
    day: 1,
    exercise: "Power Clean + Push Press",
    instruction: "65% 2+3r3s",
  },
  {
    week: 1,
    day: 1,
    exercise: "Snatch Panda Pull",
    instruction: "90% 2r3s",
  },
  {
    week: 1,
    day: 1,
    exercise: "Back Squat",
    instruction: "77% 3r3s",
  },
  {
    week: 1,
    day: 1,
    exercise: "Situps on Roman Chair or Hanging knee/leg raise",
    instruction: "RPE6 10r3s",
  },
  {
    week: 1,
    day: 2.5,
    exercise: "Muscle Snatch",
    instruction: "65% 2r3s",
  },
  {
    week: 1,
    day: 2.5,
    exercise: "Pullups",
    instruction: "4RIR3s or RPE6 6r2s",
  },
  {
    week: 1,
    day: 2.5,
    exercise: "Clean Romanian Deadlift",
    instruction: "RPE6 10r2s",
  },
  {
    week: 2,
    day: 3.5,
    exercise: "Snatch + Overhead Squat",
    instruction: "78% 1r4s",
  },
  {
    week: 2,
    day: 3.5,
    exercise: "Power Clean + Push Press",
    instruction: "70% 2+3r3s",
  },
  {
    week: 2,
    day: 3.5,
    exercise: "Snatch Panda Pull",
    instruction: "95% 2r3s",
  },
  {
    week: 2,
    day: 3.5,
    exercise: "Back Squat",
    instruction: "80% 3r4s",
  },
  {
    week: 2,
    day: 3.5,
    exercise: "Situps on Roman Chair or Hanging knee/leg raise",
    instruction: "RPE7 10r3s",
  },
]
