name: daily-db-backup

on:
  push:
    branches:
      - daily-backup-job

jobs:
  create-and-store-back-up:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: create-proxy
        run: flyctl proxy 15432:5432 -a otago-lifting-db &
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - uses: tj-actions/pg-dump@v2.3
        with:
          database_url: "postgres://postgres:${{ secrets.DATABASE_PW }}@localhost:15432/otago_weightlifting"
          path: ./apps/backend/db_scripts/backup.sql
          options: "-O"
      - run: ls ./apps/backend/db_scripts/backup.sql
          
