on:
  workflow_call:
    
jobs:
  deploy-to-fly:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./apps/backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

