name: Deploy to Fly

on:
  push:
    branches: [main]

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: superfly/flyctl-actions/setup-flyctl@master
      
    - name: Deploy to Fly
      working-directory: ./apps/backend
      run: flyctl deploy --remote-only
      env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
