name: Push to main

on:
  push:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  deploy-to-fly:
    needs:
      - tests
    uses: ./.github/workflows/deploy-to-fly.yml
    secrets: inherit
