name: Push and PR excluding main with diff

on:
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches-ignore:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  previous-commit:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-prev-commit-sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v3
      - id: get-prev-commit-sha
        run: echo $(git rev-parse @~1) && echo "sha=$(git rev-parse @~1)" >> "$GITHUB_OUTPUT"

  deploy-to-fly:
    needs:
      - previous-commit
      - tests
    uses: ./.github/workflows/deploy-to-fly.yml
    secrets: inherit
    with:
      base: ${{needs.previous-commit.outputs.sha}}
