name: Push and PR excluding main with diff

on:
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches-ignore:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  deploy-to-fly:
    needs:
      - tests
    uses: ./.github/workflows/deploy-to-fly.yml
    secrets: inherit
