on:
  workflow_call:
    
jobs:
  unit-and-integration-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'apps/backend'

    - name: Install node
      if: steps.filter.outputs.backend == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: npm
        cache-dependency-path: apps/backend/package-lock.json

    - name: Install deps
      working-directory: ./apps/backend
      run: npm ci

    - name: Unit tests
      working-directory: ./apps/backend
      run: npm run test-unit

    - name: Integration tests
      working-directory: ./apps/backend
      run: npm run test-docker-ci
      env: 
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user
        POSTGRES_DB: lifting
        SECRET: secret
        NODE_ENV: test
