name: tests

on:
  workflow_call:
    
jobs:
  docker:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: npm
        cache-dependency-path: apps/backend/package-lock.json

    - name: Install deps
      working-directory: ./apps/backend
      run: npm ci

    - name: Unit tests
      run: npm run test-unit

    - name: Integration tests
      working-directory: ./apps/backend
      run: npm run test-docker-ci
      env: 
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user
        POSTGRES_DB: lifting
        SECRET: secret
        NODE_ENV: test
